version: 2
jobs:
  build:
    working_directory: ~/demoCircleCI
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install all packages
          command: |
            sudo pip install coverage
            sudo pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python manage.py test
      - run:
          name: Run coverage report
          command: |
            coverage run manage.py test
            coverage report
            coverage html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: htmlcov